# Generated by Django 5.0.3 on 2024-03-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_ap_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AP',
            new_name='Logger',
        ),
    ]
