# Generated by Django 5.0.3 on 2024-03-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('userid', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField(help_text='your birthdate')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
